<?php

namespace Tests\Feature;

use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProductCodeGenerationTest extends TestCase
{
    use RefreshDatabase;

    public function test_generate_code_sequence_and_prefix_for_prod()
    {
        // Simulate a pre-existing code generated for this name+type
    $first = Product::generateCode('Test Product 60', Product::FORM_ROLL);
        Product::create([
            'code' => $first,
            'name' => 'Test Product 60',
            'form_type' => Product::FORM_ROLL,
            'form_type' => Product::FORM_ROLL,
            'product_type' => Product::TYPE_RAW_MATERIAL,
        ]);

        $generated = Product::generateCode('Test Product 60', 'papier_roll');

        $this->assertStringStartsWith('PROD-', $generated);
        $this->assertStringEndsWith('-002', $generated);
    }

    public function test_generate_code_prefix_cons_for_consumable()
    {
    $firstCons = Product::generateCode('Adhesive Tape 50mm', Product::FORM_CONSUMABLE);
        Product::create([
            'code' => $firstCons,
            'name' => 'Adhesive Tape 50mm',
            'form_type' => Product::FORM_CONSUMABLE,
            'form_type' => Product::FORM_CONSUMABLE,
            'product_type' => Product::TYPE_RAW_MATERIAL,
        ]);

        $generated = Product::generateCode('Adhesive Tape 50mm', 'consommable');

        $this->assertStringStartsWith('CONS-', $generated);
        $this->assertStringEndsWith('-002', $generated);
    }

    public function test_creating_product_without_code_populates_code_via_model()
    {
        $p = Product::create([
            'name' => 'Autogenerated Code Product',
            'form_type' => Product::FORM_ROLL,
            'product_type' => Product::TYPE_RAW_MATERIAL,
        ]);

        $this->assertNotEmpty($p->code);
        $this->assertStringStartsWith('PROD-', $p->code);
    }

    public function test_regenerate_code_on_form_type_update_if_auto_generated()
    {
        // Create a product without code and ensure it's generated
        $p = Product::create([
            'name' => 'Auto Regenerate 60',
            'form_type' => Product::FORM_ROLL,
            'grammage' => 60,
            'product_type' => Product::TYPE_RAW_MATERIAL,
        ]);

    $originalCode = $p->code;

    $expectedNew = Product::generateCode($p->name, $p->form_type, Product::FORM_SHEET, $p->grammage, $p->type_papier, $p->flute, $p->laize);

    // Update a tracked attribute and save
    $p->form_type = Product::FORM_SHEET;
    $p->save();

    // The next sequence may vary depending on existing codes, assert prefix+abbr matches instead
    $expectedBase = substr($expectedNew, 0, strrpos($expectedNew, '-'));
    $this->assertStringStartsWith($expectedBase, $p->fresh()->code);
    }

    public function test_manual_code_is_preserved_on_update()
    {
        $p = Product::create([
            'code' => 'CUSTOM-123',
            'name' => 'Manual Code Product',
            'form_type' => Product::FORM_ROLL,
            'grammage' => 80,
            'product_type' => Product::TYPE_RAW_MATERIAL,
        ]);

        $p->form_type = Product::FORM_SHEET;
        $p->save();

        $this->assertEquals('CUSTOM-123', $p->fresh()->code);
    }
}
