<?php

namespace App\Filament\Resources\LowStockAlerts;

use App\Filament\Resources\LowStockAlerts\Pages\CreateLowStockAlert;
use App\Filament\Resources\LowStockAlerts\Pages\EditLowStockAlert;
use App\Filament\Resources\LowStockAlerts\Pages\ListLowStockAlerts;
use App\Filament\Resources\LowStockAlerts\Schemas\LowStockAlertForm;
use App\Filament\Resources\LowStockAlerts\Tables\LowStockAlertsTable;
use App\Models\LowStockAlert;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;

class LowStockAlertResource extends Resource
{
    protected static ?string $model = LowStockAlert::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedExclamationTriangle;
    
    protected static string|\UnitEnum|null $navigationGroup = 'Gestion du Stock';
    
    protected static ?int $navigationSort = 6;
    
    public static function getNavigationLabel(): string
    {
        return 'Alertes de Stock';
    }
    
    public static function getModelLabel(): string
    {
        return 'Alerte de Stock';
    }
    
    public static function getPluralModelLabel(): string
    {
        return 'Alertes de Stock';
    }
    
    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::active()->count();
    }
    
    public static function getNavigationBadgeColor(): ?string
    {
        $count = static::getModel()::active()->count();
        
        if ($count === 0) {
            return 'success';
        }
        
        $criticalCount = static::getModel()::active()->bySeverity('CRITICAL')->count();
        
        if ($criticalCount > 0) {
            return 'danger';
        }
        
        return 'warning';
    }

    public static function form(Schema $schema): Schema
    {
        return LowStockAlertForm::configure($schema);
    }

    public static function table(Table $table): Table
    {
        return LowStockAlertsTable::configure($table);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListLowStockAlerts::route('/'),
            'edit' => EditLowStockAlert::route('/{record}/edit'),
        ];
    }
    
    public static function canCreate(): bool
    {
        return false; // Alerts are auto-generated by the CheckLowStock command
    }
}
